# Generated by Django 4.2.13 on 2024-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0001_initial")]

    operations = [migrations.AlterField(model_name="customuser", name="profile_photo", field=models.CharField(blank=True, max_length=255, null=True))]
