# Generated by Django 4.2.13 on 2024-06-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_alter_customuser_profile_photo")]

    operations = [
        migrations.AddField(model_name="customuser", name="oauth_kakao_access_token", field=models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField(model_name="customuser", name="oauth_kakao_expires_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="customuser", name="oauth_kakao_id_token", field=models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField(model_name="customuser", name="oauth_kakao_refresh_token", field=models.CharField(blank=True, max_length=255, null=True)),
    ]
