# Generated by Django 4.2.13 on 2024-08-10 12:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("community", "__first__")]

    operations = [
        migrations.CreateModel(
            name="Likes",
            fields=[
                ("likes_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("likes_date", models.DateTimeField(auto_now_add=True)),
                ("tour_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="community.tourplace")),
                ("user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
