# Generated by Django 4.2.13 on 2024-08-09 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("banner_id", models.AutoField(primary_key=True, serialize=False)),
                ("banner_img", models.CharField(max_length=255)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("banner_title", models.CharField(max_length=200)),
                ("banner_url", models.URLField()),
            ],
            options={"db_table": "Banner"},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("noti_id", models.AutoField(primary_key=True, serialize=False)),
                ("noti_title", models.TextField(blank=True, null=True)),
                ("noti_text", models.TextField(blank=True, null=True)),
                ("noti_date", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "Notification"},
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[("preference_id", models.AutoField(primary_key=True, serialize=False)), ("preference_name", models.CharField(max_length=45))],
            options={"db_table": "Preference"},
        ),
        migrations.CreateModel(
            name="TourKeyword",
            fields=[("keyword_id", models.AutoField(primary_key=True, serialize=False)), ("keyword_name", models.CharField(max_length=45))],
            options={"db_table": "TourKeyword"},
        ),
        migrations.CreateModel(
            name="TourPlace",
            fields=[
                ("tour_id", models.AutoField(primary_key=True, serialize=False)),
                ("tour_name", models.CharField(max_length=100)),
                ("tour_location", models.CharField(max_length=255)),
                ("tour_x", models.FloatField()),
                ("tour_y", models.FloatField()),
                ("tour_info", models.TextField()),
                ("tour_img", models.TextField()),
                ("tour_viewcnt", models.IntegerField(default=0)),
                ("tour_viewcnt_month", models.CharField(default="0", max_length=45)),
                ("tour_summary", models.TextField()),
                ("tour_tel", models.CharField(blank=True, max_length=45, null=True)),
                ("tour_telname", models.CharField(blank=True, max_length=45, null=True)),
                ("tour_title", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "TourPlace"},
        ),
        migrations.CreateModel(
            name="User_Preference",
            fields=[
                ("userpre_id", models.AutoField(primary_key=True, serialize=False)),
                ("preference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="preference", to="community.preference")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "User_has_Preference"},
        ),
        migrations.CreateModel(
            name="TourPlace_TourKeyword",
            fields=[
                ("placekey_id", models.IntegerField(primary_key=True, serialize=False)),
                ("keyword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tourkeyword", to="community.tourkeyword")),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tourplace", to="community.tourplace")),
            ],
            options={"db_table": "TourPlace_has_TourKeyword"},
        ),
        migrations.CreateModel(
            name="TourLog",
            fields=[
                ("tourlog_id", models.AutoField(primary_key=True, serialize=False)),
                ("tourlog_date", models.DateField()),
                ("tourlog_text", models.CharField(max_length=100)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usertourlog", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "TourLog"},
        ),
        migrations.CreateModel(
            name="PostLog",
            fields=[
                ("postlog_id", models.AutoField(primary_key=True, serialize=False)),
                ("postlog_date", models.DateField()),
                ("postlog_text", models.CharField(max_length=100)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="userpostlog", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "PostLog"},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_text", models.TextField(blank=True, null=True)),
                ("post_img", models.TextField(blank=True, null=True)),
                ("post_date", models.DateTimeField()),
                ("post_likes", models.IntegerField(default=0)),
                ("post_score", models.IntegerField(default=0, null=True)),
                ("post_hashtag", models.CharField(blank=True, max_length=100, null=True)),
                ("post_view", models.IntegerField(default=0)),
                ("last_modified", models.DateTimeField()),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tourplacepost", to="community.tourplace")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="userpost", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "Post"},
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                ("likes_id", models.AutoField(primary_key=True, serialize=False)),
                ("like_date", models.DateTimeField()),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tourplacelike", to="community.tourplace")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="userlike", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "Likes"},
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("comments_id", models.AutoField(primary_key=True, serialize=False)),
                ("comments_date", models.DateTimeField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tourplacecomment", to="community.tourplace")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usercomment", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "Comments"},
        ),
    ]
