# Generated by Django 4.2.13 on 2024-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("banner_id", models.AutoField(primary_key=True, serialize=False)),
                ("banner_img", models.CharField(max_length=255)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("banner_title", models.CharField(max_length=200)),
                ("banner_url", models.URLField()),
            ],
            options={"db_table": "Banner"},
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                ("likes_id", models.AutoField(primary_key=True, serialize=False)),
                ("like_date", models.DateTimeField()),
                ("tour_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
            options={"db_table": "Likes"},
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("search_date", models.DateField()),
                ("search_text", models.CharField(max_length=100)),
                ("user_id", models.IntegerField()),
            ],
            options={"db_table": "Log"},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("noti_id", models.AutoField(primary_key=True, serialize=False)),
                ("noti_title", models.TextField(blank=True, null=True)),
                ("noti_text", models.TextField(blank=True, null=True)),
                ("noti_date", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "Notification"},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_text", models.TextField(blank=True, null=True)),
                ("post_img", models.TextField(blank=True, null=True)),
                ("post_date", models.DateTimeField()),
                ("post_likes", models.IntegerField(default=0)),
                ("post_score", models.IntegerField(default=0, null=True)),
                ("post_hashtag", models.CharField(blank=True, max_length=100, null=True)),
                ("tour_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("post_view", models.IntegerField(default=0)),
                ("last_modified", models.DateTimeField()),
            ],
            options={"db_table": "Post"},
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[("preference_id", models.AutoField(primary_key=True, serialize=False)), ("preference_name", models.CharField(max_length=45))],
            options={"db_table": "Preference"},
        ),
        migrations.CreateModel(
            name="TourKeyword",
            fields=[("keyword_id", models.AutoField(primary_key=True, serialize=False)), ("keyword_name", models.CharField(max_length=45))],
            options={"db_table": "TourKeyword"},
        ),
        migrations.CreateModel(
            name="TourPlace",
            fields=[
                ("tour_id", models.AutoField(primary_key=True, serialize=False)),
                ("tour_name", models.CharField(max_length=100)),
                ("tour_location", models.CharField(max_length=255)),
                ("tour_x", models.FloatField()),
                ("tour_y", models.FloatField()),
                ("tour_info", models.TextField()),
                ("tour_img", models.TextField()),
                ("tour_viewcnt", models.IntegerField(default=0)),
                ("tour_viewcnt_month", models.CharField(default="0", max_length=45)),
                ("tour_summary", models.TextField()),
                ("tour_tel", models.CharField(blank=True, max_length=45, null=True)),
                ("tour_telname", models.CharField(blank=True, max_length=45, null=True)),
                ("tour_title", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "TourPlace"},
        ),
        migrations.CreateModel(
            name="TourPlace_has_TourKeyword",
            fields=[
                ("placekey_id", models.IntegerField(primary_key=True, serialize=False)),
                ("tour_id", models.IntegerField()),
                ("keyword_id", models.IntegerField()),
            ],
            options={"db_table": "TourPlace_has_TourKeyword"},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_login_id", models.CharField(max_length=45)),
                ("user_login_pw", models.CharField(max_length=45)),
                ("user_token", models.TextField()),
                ("user_profilephoto", models.TextField(blank=True, null=True)),
                ("user_nickname", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "User"},
        ),
        migrations.CreateModel(
            name="User_has_Preference",
            fields=[
                ("userpre_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("preference_id", models.IntegerField()),
            ],
            options={"db_table": "User_has_Preference"},
        ),
    ]
